FROM rust:alpine3.19

# Install build dependencies
RUN apk add --no-cache \
    musl-dev \
    openssl-dev \
    openssl-libs-static \
    pkgconfig \
    perl \
    make \
    gcc \
    g++ \
    linux-headers \
    git

# Set environment for static linking
ENV OPENSSL_STATIC=1
ENV OPENSSL_LIB_DIR=/usr/lib
ENV OPENSSL_INCLUDE_DIR=/usr/include
ENV PKG_CONFIG_ALL_STATIC=1
ENV RUSTFLAGS="-C target-feature=+crt-static"

# Add musl target explicitly
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /build
